---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# charts

<!-- badges: start -->
<!-- badges: end -->

The goal of charts is to create BR charts in the publication: Colopy MW, Gakava L, Chen C. Planning Benefit-Risk Assessments Using Visualizations. Ther Innov Regul Sci. 2023 Nov;57(6):1123-1135. doi: 10.1007/s43441-023-00563-9. Epub 2023 Sep 8. PMID: 37682462.

## Installation

You can install the development version of charts from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("BR-Visualization/charts")
```

## Figure 2 - Demographics (Pyramid Chart)

```{r pyramid_plot, echo = FALSE}
charts::demography |>
  dplyr::mutate(
    figprev = ifelse(
      .data[["Gender"]] == "Females", -1 * .data[["Prevalence"]] / 100000, .data[["Prevalence"]] / 100000
    ),
    Sex = .data[["Gender"]]
  ) |>
  charts::pyramid_chart(Typev = c("A", "B"), gendervar = "Sex", alpha_set = 0.7)
```

## Figure 4 - Comorbidities (Grouped Bar Chart)

```{r grouped_barchart, echo = FALSE}
charts::grouped_barchart(
  data = charts::comorbidities, xvar = "Comorbidities",
  yvar = "Prevalence", groupvar = "Severity",
  chartcolors = colfun()$fig4_colors
)
```
